# Generated by Django 3.0.4 on 2020-05-26 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
